# Generated by Django 5.0.2 on 2024-02-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sumadhura_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
